const articles = [
  {
    "id": "lesson-ccna001-03",
    "content_th": "## TCP/IP Protocol Suite\n\n**บทนำ**\nTCP/IP Protocol Suite เป็นรากฐานของการสื่อสารในเครือข่ายคอมพิวเตอร์และอินเทอร์เน็ต ถูกออกแบบมาเพื่อให้ระบบต่างๆ สามารถสื่อสารกันได้แม้จะต่างแพลตฟอร์ม\n\n**โครงสร้างเลเยอร์ (Layer Architecture)**\nประกอบด้วย 4 เลเยอร์หลัก:\n- **Application Layer:** เทียบเท่ากับ Layer 5-7 ของ OSI Model จัดการกับโปรโตคอลระดับผู้ใช้งาน เช่น HTTP, FTP\n- **Transport Layer:** จัดการการเชื่อมต่อระหว่าง Host มี 2 โปรโตคอลหลักคือ TCP (เชื่อถือได้) และ UDP (รวดเร็ว)\n- **Internet Layer:** เทียบเท่า Network Layer ทำหน้าที่ค้นหาเส้นทางและระบุ IP Address\n- **Network Access Layer:** จัดการกับฮาร์ดแวร์และการส่งข้อมูลบนสื่อกายภาพ\n\n**สรุป**\nTCP/IP คือโมเดลที่ใช้งานจริงในปัจจุบัน ซึ่งมีความเรียบง่ายและยืดหยุ่นกว่า OSI Model ทำให้กลายมาเป็นมาตรฐานสากลของระบบเครือข่าย",
    "content_en": "## TCP/IP Protocol Suite\n\n**Introduction**\nThe TCP/IP Protocol Suite is the foundation of computer networking and the Internet. It is designed to enable communication between disparate systems across the globe.\n\n**Layer Architecture**\nIt consists of 4 primary layers:\n- **Application Layer:** Corresponds to OSI Layers 5-7. Handles high-level protocols like HTTP, DNS, and FTP.\n- **Transport Layer:** Manages host-to-host communication. The main protocols are TCP (reliable connection-oriented) and UDP (fast connectionless).\n- **Internet Layer:** Equivalent to the OSI Network layer. Handles logical addressing (IP) and routing.\n- **Network Access Layer:** Deals with physical hardware and MAC addressing.\n\n**Summary**\nTCP/IP is the practical, real-world model used today. Its simplicity and flexibility compared to the OSI model have made it the universal standard for networking."
  },
  {
    "id": "lesson-ccna002-04",
    "content_th": "## Spanning Tree Protocol (STP)\n\n**บทนำ**\nSpanning Tree Protocol (STP) คือโปรโตคอลใน Layer 2 ที่ออกแบบมาเพื่อป้องกันปัญหา Loop ที่เกิดขึ้นในสวิตช์เครือข่าย เมื่อมีการเชื่อมต่อสายแลนซ้ำซ้อน (Redundancy)\n\n**หลักการทำงานของ STP**\n- **การเลือก Root Bridge:** สวิตช์ที่มีค่า Bridge ID ต่ำที่สุดจะถูกเลือกเป็นศูนย์กลาง (Root Bridge)\n- **Port Roles:** พอร์ตต่างๆ จะถูกกำหนดบทบาท เช่น Root Port (เส้นทางที่ดีที่สุดไป Root), Designated Port (พอร์ตส่งข้อมูล) และ Blocking Port (พอร์ตที่ถูกบล็อกเพื่อกัน Loop)\n- **BPDU:** สวิตช์จะส่งข้อความ BPDU หากันเพื่อแลกเปลี่ยนข้อมูลและปรับเปลี่ยนโครงสร้าง Spanning Tree เมื่อมีสายขาด\n\n**สรุป**\nSTP เป็นกลไกสำคัญที่ขาดไม่ได้ในเครือข่ายแบบสวิตชิ่ง ช่วยให้เครือข่ายมี Redundancy ได้โดยไม่เกิดปัญหา Broadcast Storm ที่อาจทำให้ระบบล่ม",
    "content_en": "## Spanning Tree Protocol (STP)\n\n**Introduction**\nSpanning Tree Protocol (STP) is a Layer 2 network protocol designed to prevent loops in switched networks while allowing for physical path redundancy.\n\n**How STP Works**\n- **Root Bridge Election:** The switch with the lowest Bridge ID becomes the logical center of the network.\n- **Port Roles:** Ports are assigned specific roles: Root Port (best path to the root), Designated Port (forwarding traffic), and Blocking Port (blocks traffic to prevent loops).\n- **BPDU:** Switches exchange Bridge Protocol Data Units (BPDUs) to monitor the network state and automatically adapt if a link fails.\n\n**Summary**\nSTP is critical for maintaining a stable Layer 2 environment. It allows network engineers to build redundant topologies without the fear of broadcast storms taking down the network."
  },
  {
    "id": "lesson-ccna003-03",
    "content_th": "## RIP (Routing Information Protocol)\n\n**บทนำ**\nRIP เป็นหนึ่งใน Routing Protocol แบบ Distance Vector ที่เก่าแก่ที่สุด ออกแบบมาสำหรับเครือข่ายขนาดเล็กถึงขนาดกลาง\n\n**คุณสมบัติหลัก**\n- **Metric:** ใช้จำนวน Hop (Hop Count) เป็นเกณฑ์ในการเลือกเส้นทาง โดยเส้นทางที่มีจำนวน Hop น้อยที่สุดจะถือว่าดีที่สุด\n- **ข้อจำกัด:** รองรับสูงสุดเพียง 15 Hop (16 ถือว่า Unreachable)\n- **RIPv1 vs RIPv2:** RIPv1 เป็นแบบ Classful (ไม่ส่ง Subnet mask) ส่วน RIPv2 รองรับ Classless Inter-Domain Routing (CIDR) และการทำ Authentication\n\n**ตัวอย่างการตั้งค่าเบื้องต้น**\n```text\nRouter(config)# router rip\nRouter(config-router)# version 2\nRouter(config-router)# network 192.168.1.0\n```\n\n**สรุป**\nแม้ในปัจจุบันองค์กรใหญ่ๆ จะหันไปใช้ OSPF หรือ EIGRP แต่ RIP ยังคงเป็นโปรโตคอลพื้นฐานที่สำคัญในการศึกษาทำความเข้าใจหลักการทำงานของ Dynamic Routing",
    "content_en": "## RIP (Routing Information Protocol)\n\n**Introduction**\nRIP is one of the oldest Distance Vector routing protocols, primarily designed for small to medium-sized networks.\n\n**Key Features**\n- **Metric:** It uses Hop Count as its routing metric. The path with the fewest routers (hops) to cross is considered the best.\n- **Limitation:** The maximum allowable hop count is 15. A hop count of 16 is considered infinite (unreachable).\n- **RIPv1 vs RIPv2:** RIPv1 is classful (does not send subnet masks in updates). RIPv2 is classless, supports VLSM/CIDR, and allows for authentication.\n\n**Basic Configuration Example**\n```text\nRouter(config)# router rip\nRouter(config-router)# version 2\nRouter(config-router)# network 192.168.1.0\n```\n\n**Summary**\nWhile large enterprises favor OSPF or EIGRP, RIP remains a fundamental protocol for understanding the core concepts of dynamic routing and distance vector algorithms."
  },
  {
    "id": "lesson-ccna004-04",
    "content_th": "## WAN Design and Redundancy\n\n**บทนำ**\nเครือข่ายบริเวณกว้าง (WAN) คือระบบที่เชื่อมต่อสาขาต่างๆ ขององค์กรเข้าด้วยกัน การออกแบบ WAN ต้องคำนึงถึงความเสถียรและความพร้อมใช้งานสูง\n\n**รูปแบบการออกแบบ (Topologies)**\n- **Hub and Spoke:** สำนักงานใหญ่เป็นศูนย์กลาง (Hub) และสาขา (Spoke) เชื่อมเข้ามา จัดการง่ายแต่มี Single Point of Failure\n- **Full Mesh:** ทุกสาขาเชื่อมถึงกันหมด เสถียรที่สุดแต่มีค่าใช้จ่ายสูง\n- **Partial Mesh:** ผสมผสานเพื่อลดต้นทุน โดยเชื่อมเฉพาะสาขาสำคัญเข้าด้วยกัน\n\n**ความสำคัญของ Redundancy**\nการออกแบบเครือข่ายสำรอง (Dual-homed หรือ Dual-WAN) ช่วยรับประกันว่าระบบจะทำงานได้ต่อเนื่องหากลิงก์หลักเกิดปัญหา โดยมักใช้ร่วมกับโปรโตคอลเช่น BGP หรือการทำ SD-WAN ในปัจจุบัน\n\n**สรุป**\nการออกแบบ WAN ที่ดีต้องรักษาสมดุลระหว่างประสิทธิภาพ ค่าใช้จ่าย และความน่าเชื่อถือ โดยการวางแผน Redundancy ถือเป็นหัวใจสำคัญ",
    "content_en": "## WAN Design and Redundancy\n\n**Introduction**\nWide Area Networks (WANs) connect dispersed organizational sites. Designing an effective WAN requires a focus on high availability, performance, and redundancy.\n\n**Design Topologies**\n- **Hub and Spoke:** The headquarters acts as a central hub for remote spoke branches. It is cost-effective but creates a single point of failure.\n- **Full Mesh:** Every site connects to every other site. It provides maximum redundancy but is extremely expensive and complex to scale.\n- **Partial Mesh:** A hybrid approach where only critical sites have multiple direct connections, balancing cost and reliability.\n\n**Importance of Redundancy**\nImplementing redundant paths (like Dual-homed or Dual-router setups) ensures network survivability if a primary link fails. Modern architectures heavily leverage SD-WAN to manage these links dynamically.\n\n**Summary**\nA robust WAN design strikes a balance between performance, budget, and reliability. Integrating proper redundancy mechanisms is critical to maintaining continuous business operations."
  },
  {
    "id": "lesson-ccna005-05",
    "content_th": "## NTP and Syslog\n\n**บทนำ**\nNetwork Time Protocol (NTP) และ Syslog เป็นสองบริการเครือข่ายพื้นฐานที่ทำงานร่วมกันเพื่อการดูแลและตรวจสอบระบบอย่างมีประสิทธิภาพ\n\n**Network Time Protocol (NTP)**\n- ทำหน้าที่ซิงโครไนซ์เวลาของอุปกรณ์ทุกชิ้นในเครือข่ายให้ตรงกัน\n- ใช้สถาปัตยกรรมแบบ Stratum (Stratum 0 คือนาฬิกาอ้างอิง, Stratum 1 คือเซิร์ฟเวอร์ที่รับเวลามา)\n- สำคัญมากสำหรับการยืนยันตัวตนและการแก้ปัญหา (Troubleshooting)\n\n**Syslog**\n- เป็นมาตรฐานการเก็บและส่ง Log ของระบบไปยังเซิร์ฟเวอร์ส่วนกลาง\n- มีระดับความรุนแรง (Severity Levels) 8 ระดับ (0 ถึง 7) เช่น Level 0 (Emergencies), Level 3 (Errors), และ Level 7 (Debugging)\n\n**สรุป**\nหากไม่มี NTP เวลาใน Log จะคลาดเคลื่อน ทำให้ไม่สามารถนำข้อมูลจาก Syslog ของอุปกรณ์หลายๆ ตัวมาหาความสัมพันธ์ (Correlation) เพื่อวิเคราะห์หาสาเหตุของปัญหาในเครือข่ายได้",
    "content_en": "## NTP and Syslog\n\n**Introduction**\nNetwork Time Protocol (NTP) and Syslog are two foundational network services that work hand-in-hand for effective network management, monitoring, and troubleshooting.\n\n**Network Time Protocol (NTP)**\n- Synchronizes the clocks of all networking devices to a highly accurate time source.\n- Operates on a hierarchical system called Stratum levels (Stratum 1 servers get time directly from hardware clocks, Stratum 2 gets it from Stratum 1, etc.).\n- Critical for time-sensitive protocols and log accuracy.\n\n**Syslog**\n- A standard for message logging that allows devices to send event messages to a centralized logging server.\n- Uses Severity Levels ranging from 0 (Emergencies) to 7 (Debugging).\n\n**Summary**\nWithout NTP, the timestamps on Syslog messages will be incorrect or mismatched across devices, making it nearly impossible to correlate events and perform accurate root-cause analysis during outages."
  },
  {
    "id": "lesson-ccna006-04",
    "content_th": "## AAA Framework\n\n**บทนำ**\nAAA ย่อมาจาก Authentication, Authorization และ Accounting เป็นเฟรมเวิร์กมาตรฐานสำหรับการควบคุมการเข้าถึงระบบเครือข่ายและการรักษาความปลอดภัย\n\n**องค์ประกอบของ AAA**\n- **Authentication (การยืนยันตัวตน):** ตรวจสอบว่าผู้ใช้คือใคร (เช่น การใช้ Username/Password, OTP หรือ Certificate)\n- **Authorization (การมอบสิทธิ์):** กำหนดว่าผู้ใช้สามารถทำอะไรได้บ้างหลังจากยืนยันตัวตนสำเร็จ (เช่น สิทธิ์ในการตั้งค่า หรือแค่สิทธิ์ในการอ่าน)\n- **Accounting (การเก็บบันทึก):** บันทึกการกระทำของผู้ใช้ เช่น ล็อกอินเมื่อไหร่ พิมพ์คำสั่งอะไรไปบ้าง และใช้เวลานานเท่าไร\n\n**RADIUS vs TACACS+**\n- **RADIUS:** เป็นมาตรฐานเปิด นิยมใช้กับการเข้าถึงเครือข่าย (Network Access) เช่น Wi-Fi 802.1x\n- **TACACS+:** เป็นโปรโตคอลของ Cisco ที่แยก A-A-A ออกจากกันอย่างชัดเจน นิยมใช้ควบคุมสิทธิ์การเข้าบริหารจัดการอุปกรณ์ (Device Administration)\n\n**สรุป**\nAAA เป็นหัวใจสำคัญของ Security Policyในองค์กร ช่วยให้ผู้ดูแลระบบควบคุมและตรวจสอบทุกการกระทำในเครือข่ายได้อย่างรัดกุม",
    "content_en": "## AAA Framework\n\n**Introduction**\nThe AAA Framework stands for Authentication, Authorization, and Accounting. It is the core architectural framework used for access control and network security.\n\n**Components of AAA**\n- **Authentication:** Verifies 'Who you are' (using credentials like passwords, biometrics, or certificates).\n- **Authorization:** Determines 'What you can do.' It restricts the commands or resources a user can access after authenticating.\n- **Accounting:** Tracks 'What you did.' It records login/logout times, commands executed, and resources consumed for auditing purposes.\n\n**RADIUS vs TACACS+**\n- **RADIUS:** An open standard primarily used for network access control (like Wi-Fi 802.1X). It combines authentication and authorization.\n- **TACACS+:** A Cisco-proprietary protocol that separates the three AAA functions completely. It is heavily preferred for device administration.\n\n**Summary**\nThe AAA framework is essential for enterprise security. It ensures only authorized personnel can access infrastructure, restricts their privileges appropriately, and provides a full audit trail of their actions."
  },
  {
    "id": "lesson-adv002-04",
    "content_th": "## EIGRP Route Filtering and Summarization\n\n**บทนำ**\nEIGRP เป็น Routing Protocol แบบ Advanced Distance Vector การจัดการตารางเส้นทาง (Routing Table) ให้มีขนาดเล็กและมีประสิทธิภาพถือเป็นทักษะระดับสูงใน EIGRP\n\n**Route Filtering**\n- ใช้เพื่อบล็อกหรือไม่ยอมรับบางเส้นทางเข้ามาในระบบ\n- ทำได้ผ่านการใช้ `Prefix-list`, `Access-list`, หรือ `Route-map` ร่วมกับคำสั่ง `distribute-list`\n- ช่วยเพิ่มความปลอดภัยและควบคุมทิศทางของทราฟฟิก\n\n**Manual Summarization**\n- เป็นการรวมหลายซับเน็ตให้เป็นเส้นทางเดียว (Summary Route) ก่อนประกาศออกไป\n- ทำได้โดยใช้คำสั่งระดับอินเตอร์เฟส เช่น `ip summary-address eigrp <AS> <IP> <Mask>`\n- **ข้อดี:** ลดขนาด Routing table, ช่วยจำกัดขอบเขตของ EIGRP Query เมื่อมีเส้นทางดาวน์ลง (ลดอาการ Stuck-in-Active)\n\n**สรุป**\nการประยุกต์ใช้ Filtering และ Summarization ร่วมกันใน EIGRP ช่วยเพิ่มความเสถียรของเครือข่าย ลดภาระของ CPU บนเร้าเตอร์ และควบคุมเส้นทางการเชื่อมต่อได้อย่างสมบูรณ์แบบ",
    "content_en": "## EIGRP Route Filtering and Summarization\n\n**Introduction**\nEIGRP is an Advanced Distance Vector routing protocol. Managing the size and efficiency of the routing table is a crucial advanced skill in EIGRP networks.\n\n**Route Filtering**\n- Used to permit or deny specific routes from being installed or advertised.\n- Typically implemented using `Prefix-lists`, `Access-lists`, or `Route-maps` applied via a `distribute-list` command.\n- Improves security and enforces traffic engineering policies.\n\n**Manual Summarization**\n- The process of consolidating multiple specific subnets into a single larger aggregate route.\n- In EIGRP, this is configured at the interface level using `ip summary-address eigrp <AS> <IP> <Mask>`.\n- **Benefits:** Shrinks the routing table, hides topology changes, and restricts the boundary of EIGRP Queries, significantly reducing the chance of Stuck-in-Active (SIA) errors.\n\n**Summary**\nCombining route filtering and manual summarization optimizes EIGRP domains. It minimizes router CPU overhead, limits fault domains, and provides precise control over path selection."
  },
  {
    "id": "lesson-adv003-05",
    "content_th": "## BGP Filtering and Route Maps\n\n**บทนำ**\nBorder Gateway Protocol (BGP) คือโปรโตคอลหลักที่ขับเคลื่อนอินเทอร์เน็ต เนื่องจากตารางเส้นทางอินเทอร์เน็ตมีขนาดใหญ่มาก (Full Route หลักล้านเส้นทาง) การควบคุมเส้นทางด้วย Filtering จึงเป็นสิ่งที่ขาดไม่ได้\n\n**เครื่องมือสำหรับ BGP Filtering**\n- **Prefix-lists:** นิยมใช้คัดกรองตาม IP Prefix และ Subnet mask ได้อย่างแม่นยำ\n- **AS-Path ACLs:** ใช้คัดกรองจากหมายเลข AS Number ด้วย Regular Expression (Regex) เช่น ยอมรับเฉพาะเส้นทางที่มาจาก AS ถัดไปเท่านั้น\n- **Route Maps:** เป็นเครื่องมือที่ทรงพลังที่สุด ทำหน้าที่เหมือนชุดคำสั่ง IF-THEN\n\n**การประยุกต์ใช้ Route Maps**\nRoute Maps สามารถจับคู่ (Match) เส้นทางด้วย Prefix-list จากนั้นจึงกระทำ (Set) การเปลี่ยนแปลงค่า BGP Attributes เช่น Local Preference, MED หรือ AS-Path Prepending เพื่อจัดการเส้นทาง (Traffic Engineering)\n\n**สรุป**\nBGP Filtering และ Route Maps เป็นเครื่องมือระดับผู้เชี่ยวชาญที่ช่วยให้องค์กรควบคุมได้อย่างเต็มที่ว่า จะรับข้อมูลจากที่ไหน และจะส่งทราฟฟิกออกไปยังผู้ให้บริการ (ISP) รายใด",
    "content_en": "## BGP Filtering and Route Maps\n\n**Introduction**\nBorder Gateway Protocol (BGP) is the protocol that runs the Internet. Because the global Internet routing table contains over a million routes, route filtering is an absolute necessity to conserve resources and enforce policies.\n\n**BGP Filtering Tools**\n- **Prefix-lists:** Highly efficient and widely used for filtering exact IPs and subnet lengths.\n- **AS-Path ACLs:** Uses Regular Expressions (Regex) to filter routes based on the AS-Path attribute (e.g., matching only routes originated by a direct peer).\n- **Route Maps:** The most powerful tool for BGP policy implementation, functioning like complex IF-THEN scripting.\n\n**Using Route Maps**\nRoute Maps can match specific routes (using prefix-lists) and then set or manipulate BGP Attributes like Local Preference, MED, or perform AS-Path Prepending. This is the foundation of BGP Traffic Engineering.\n\n**Summary**\nBGP Filtering combined with Route Maps gives engineers granular control over outbound and inbound traffic flows, ensuring optimal path selection and enforcing peering agreements with ISPs."
  },
  {
    "id": "lesson-dev002-04",
    "content_th": "## Ansible for Network Automation\n\n**บทนำ**\nAnsible เป็นเครื่องมือโอเพนซอร์สจาก Red Hat ที่ได้รับความนิยมสูงสุดในสายงาน Network Automation เนื่องจากใช้งานง่าย ไม่ต้องเขียนโค้ดซับซ้อน และที่สำคัญคือเป็นแบบ Agentless\n\n**สถาปัตยกรรมและการทำงาน**\n- **Agentless:** ไม่ต้องติดตั้งซอฟต์แวร์บนเร้าเตอร์หรือสวิตช์ Ansible ใช้ SSH เข้าไปสั่งงานโดยตรง\n- **Playbooks:** เขียนเป็นภาษา YAML ที่อ่านง่ายเหมือนภาษาคน\n- **Inventory:** ไฟล์ระบุรายชื่อและกลุ่มของอุปกรณ์ที่ต้องการจัดการ\n- **Modules:** มีโมดูลสำหรับอุปกรณ์เครือข่ายโดยเฉพาะ เช่น `ios_config`, `nxos_command`, `eos_facts`\n\n**ตัวอย่างการใช้งาน**\nการใช้ Ansible เพื่อคอนฟิก VLAN, สำรองข้อมูลคอนฟิก (Backup), หรือการตรวจสอบสถานะ (Show commands) บนอุปกรณ์นับร้อยตัวได้พร้อมๆ กันในเวลาไม่กี่นาที\n\n**สรุป**\nAnsible ช่วยลดข้อผิดพลาดจากมนุษย์ (Human Error) และลดระยะเวลาในการทำงานแบบซ้ำซาก ทำให้วิศวกรเครือข่ายมีเวลาโฟกัสกับการออกแบบระบบมากขึ้น",
    "content_en": "## Ansible for Network Automation\n\n**Introduction**\nAnsible, developed by Red Hat, is arguably the most popular open-source tool for Network Automation. Its widespread adoption is due to its simplicity, human-readable syntax, and Agentless architecture.\n\n**Architecture and Components**\n- **Agentless:** Requires no software installation on target routers or switches. It connects via standard SSH or API.\n- **Playbooks:** Automation scripts written in YAML (Yet Another Markup Language), making them extremely easy to read and write.\n- **Inventory:** A file that defines the host devices and groups them logically.\n- **Modules:** Pre-built code blocks for specific tasks. Networking heavily uses modules like `ios_config`, `nxos_command`, and `junos_facts`.\n\n**Use Cases**\nDeploying global config changes (like Syslog/NTP), performing automated configuration backups, and gathering network state across hundreds of devices simultaneously.\n\n**Summary**\nAnsible empowers network engineers to shift from manual CLI configuration to Infrastructure as Code (IaC). It drastically reduces human error, ensures consistency, and accelerates deployment times."
  },
  {
    "id": "lesson-git-02",
    "content_th": "## GitHub & GitLab Workflows\n\n**บทนำ**\nเมื่อวงการเครือข่ายก้าวเข้าสู่ยุค NetDevOps (Network + DevOps) การจัดการซอร์สโค้ด (Source Control) จึงเข้ามามีบทบาท GitHub และ GitLab เป็นแพลตฟอร์มหลักที่ใช้หลักการของ Git\n\n**การจัดการด้วย Git Workflow**\n- **Branching:** เมื่อต้องการเปลี่ยนคอนฟิก วิศวกรจะไม่แก้ไขในระบบจริง แต่จะแตก Branch ใหม่ขึ้นมา\n- **Pull Requests (PR) / Merge Requests (MR):** หลังจากแก้ไฟล์เสร็จ จะเปิดการขอรวมโค้ด (PR/MR) เพื่อให้เพื่อนร่วมทีมช่วยตรวจสอบ (Code Review) ก่อนนำไปใช้จริง\n- **CI/CD Pipeline:** สามารถผูกเข้ากับ GitLab CI หรือ GitHub Actions เพื่อให้เมื่อมีการผ่าน PR ระบบจะรัน Ansible หรือ Python สคริปต์ไปตั้งค่าบนอุปกรณ์จริงอัตโนมัติ\n\n**สรุป**\nGitHub และ GitLab workflows เปลี่ยนวิธีการทำงานของวิศวกรเครือข่ายให้มีมาตรฐาน มีประวัติการแก้ไขชัดเจน และมีความปลอดภัยเทียบเท่ากับการพัฒนาซอฟต์แวร์ระดับองค์กร",
    "content_en": "## GitHub & GitLab Workflows\n\n**Introduction**\nAs the networking industry evolves into NetDevOps, version control systems have become fundamental. GitHub and GitLab are the leading platforms utilizing Git to manage network configurations as code.\n\n**The Git Workflow for Networks**\n- **Branching:** Instead of making live CLI changes, engineers create a separate branch to update configuration templates.\n- **Pull Requests (PR) / Merge Requests (MR):** Once changes are drafted, a PR/MR is opened. This triggers a Code Review process where peers validate the proposed configuration changes.\n- **CI/CD Pipelines:** Integrated tools like GitLab CI or GitHub Actions can automatically test configurations (using tools like Batfish) and deploy them to production routers upon merge approval.\n\n**Summary**\nAdopting GitHub/GitLab workflows brings software engineering discipline to network management. It provides full audit trails, peer reviews, and automated testing, greatly enhancing network reliability and security."
  },
  {
    "id": "lesson-sec002-04",
    "content_th": "## SSL VPN and AnyConnect\n\n**บทนำ**\nในยุคการทำงานทางไกล (Remote Work) VPN เป็นเครื่องมือที่สำคัญ SSL VPN เป็นเทคโนโลยีที่ช่วยให้ผู้ใช้งานภายนอกเชื่อมต่อเข้ามายังเครือข่ายองค์กรได้อย่างปลอดภัยผ่านโปรโตคอล TLS/SSL\n\n**รูปแบบของ SSL VPN**\n- **Clientless SSL VPN:** เข้าถึงผ่านเว็บเบราว์เซอร์ ไม่ต้องติดตั้งโปรแกรม เหมาะสำหรับการเข้าถึงเว็บแอปพลิเคชันภายใน\n- **Client-based SSL VPN:** ต้องใช้ซอฟต์แวร์เช่น **Cisco AnyConnect Secure Mobility Client** ซึ่งจะจำลองการเชื่อมต่อเสมือนว่าคอมพิวเตอร์นั้นนั่งอยู่ในออฟฟิศจริงๆ (ได้ IP จากวงภายใน)\n\n**จุดเด่นของ Cisco AnyConnect**\nนอกจากฟังก์ชัน VPN แล้ว AnyConnect ยังสามารถตรวจสอบความปลอดภัยของเครื่องไคลเอนต์ (Posture Assessment) เช่น ต้องมีแอนตี้ไวรัส หรืออัปเดต Windows ล่าสุดก่อน ถึงจะยอมให้เชื่อมต่อ\n\n**สรุป**\nSSL VPN ใช้งานง่ายกว่า IPsec VPN แบบดั้งเดิมมาก เนื่องจากไม่ต้องกังวลเรื่องการตั้งค่าพอร์ตบนฝั่งผู้ใช้งาน และ AnyConnect ช่วยยกระดับความปลอดภัยให้องค์กรได้อย่างดีเยี่ยม",
    "content_en": "## SSL VPN and AnyConnect\n\n**Introduction**\nWith the rise of remote work, VPNs are indispensable. SSL VPN technology allows remote users to securely access corporate network resources over the internet using TLS/SSL encryption.\n\n**Types of SSL VPNs**\n- **Clientless SSL VPN:** Accessed via a standard web browser. No software installation is required, making it perfect for accessing internal web apps securely.\n- **Client-based SSL VPN:** Requires a dedicated application like the **Cisco AnyConnect Secure Mobility Client**. It provides full network access by assigning an internal IP address to the remote machine.\n\n**Features of Cisco AnyConnect**\nBeyond basic VPN capabilities, AnyConnect offers advanced endpoint security features like Posture Assessment. It can verify that a client machine has an active antivirus and updated OS before granting network access.\n\n**Summary**\nSSL VPNs are much easier to deploy and traverse firewalls more reliably than traditional IPsec client VPNs. Cisco AnyConnect provides a seamless, highly secure remote access solution for modern enterprises."
  },
  {
    "id": "lesson-ts002-04",
    "content_th": "## EEM and SPAN\n\n**บทนำ**\nในกระบวนการ Troubleshooting และการมอนิเตอร์บนอุปกรณ์ Cisco เครื่องมืออย่าง EEM และ SPAN ถือเป็นตัวช่วยที่มีประสิทธิภาพสูงมาก\n\n**Embedded Event Manager (EEM)**\n- เป็นระบบรันสคริปต์อัตโนมัติที่ฝังมาใน Cisco IOS\n- ทำงานแบบ Trigger-Action เช่น หากพบว่าอินเทอร์เฟสดาวน์ (Trigger) ให้ทำการสั่งเปิดพอร์ตสำรองและส่งอีเมลแจ้งเตือน (Action)\n- ช่วยลดเวลา Downtime ได้อย่างรวดเร็วโดยไม่ต้องรอแอดมิน\n\n**Switch Port Analyzer (SPAN)**\n- หรือที่เรียกว่า Port Mirroring คือการทำสำเนาข้อมูล (Traffic) จากพอร์ตหนึ่งไปยังอีกพอร์ตหนึ่งที่เสียบเครื่องมือวิเคราะห์ (เช่น Wireshark)\n- มีทั้งแบบ Local SPAN (อยู่ในสวิตช์เดียวกัน) และ RSPAN (ส่งข้ามสวิตช์ผ่านทาง VLAN)\n\n**สรุป**\nEEM ให้ความสามารถในการตอบสนองปัญหาอัตโนมัติบนตัวอุปกรณ์เอง ในขณะที่ SPAN เปิดโอกาสให้วิศวกรสามารถดักจับแพ็กเก็ตเพื่อวิเคราะห์ปัญหาเชิงลึก ทั้งสองอย่างเป็นเครื่องมือสำคัญสำหรับผู้ดูแลระบบเครือข่ายชั้นสูง",
    "content_en": "## EEM and SPAN\n\n**Introduction**\nFor advanced troubleshooting and network monitoring on Cisco devices, Embedded Event Manager (EEM) and Switch Port Analyzer (SPAN) are incredibly powerful tools.\n\n**Embedded Event Manager (EEM)**\n- A feature embedded directly into Cisco IOS that enables on-device automation.\n- It operates on an Event-Action model. For example, if a specific Syslog message appears (Trigger), EEM can automatically execute CLI commands to clear an interface or send an alert (Action).\n- Greatly reduces MTTR (Mean Time To Repair) without requiring an external automation server.\n\n**Switch Port Analyzer (SPAN)**\n- Commonly known as Port Mirroring. It copies traffic passing through a specific port or VLAN and sends it to a destination port connected to a packet analyzer (like Wireshark).\n- Exists as Local SPAN (within a single switch) and RSPAN (mirrored across the network via a dedicated VLAN).\n\n**Summary**\nEEM provides intelligent, automated reaction capabilities right on the hardware. SPAN grants deep visibility into packet-level traffic. Together, they form a robust toolkit for proactive network defense and deep-dive troubleshooting."
  }
];

module.exports = articles;
